# Generated by Django 5.0.2 on 2024-10-05 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('sender', 'Sender'), ('receiver', 'Receiver')], default='sender', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(limit_choices_to={'role': 'receiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to='accounts.application')),
                ('sender', models.ForeignKey(limit_choices_to={'role': 'sender'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to='accounts.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver', 'user')},
            },
        ),
    ]
